version: "3"

services:
  jekyll:
    build:
      context: .
    command: jekyll serve --baseurl="" --watch --force_polling --port 8080 -H 0.0.0.0 --livereload --livereload-port 35729 --verbose
    volumes:
      - .:/srv/jekyll
    ports:
      - "8080:8080"
      - "35729:35729"
    environment:
      RUBYOPT: "-W0"
      JEKYLL_ENV: production
